//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PromotionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PromotionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.PromotionResource", typeof(PromotionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occured  In Get Promotion.
        /// </summary>
        internal static string ERROREMESSAGE_PROMOTION_INTERNAL {
            get {
                return ResourceManager.GetString("ERROREMESSAGE_PROMOTION_INTERNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Request Not Valid.
        /// </summary>
        internal static string PROMOTION_NOT_VALID {
            get {
                return ResourceManager.GetString("PROMOTION_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Retirved Successfuly.
        /// </summary>
        internal static string SUCCESSMESSAGE_DATA_RETIRVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("SUCCESSMESSAGE_DATA_RETIRVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Created Successfully.
        /// </summary>
        internal static string SUCCESSMESSAGE_PROMOTION_CREATED {
            get {
                return ResourceManager.GetString("SUCCESSMESSAGE_PROMOTION_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Deleted Successfully.
        /// </summary>
        internal static string SUCCESSMESSAGE_PROMOTION_DELETED {
            get {
                return ResourceManager.GetString("SUCCESSMESSAGE_PROMOTION_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Updated Successfully.
        /// </summary>
        internal static string SUCCESSMESSAGE_PROMOTION_UPDATED {
            get {
                return ResourceManager.GetString("SUCCESSMESSAGE_PROMOTION_UPDATED", resourceCulture);
            }
        }
    }
}
